# Generated by Django 4.0.2 on 2022-02-26 06:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(blank=True, default='', help_text='Enter 10 digits, without any special characters', max_length=10, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Phone number')),
                ('looking_for', models.TextField()),
                ('anything_else', models.TextField()),
                ('availability', models.ManyToManyField(to='configuration.SectionTime')),
                ('interests', models.ManyToManyField(related_name='interests', to='configuration.Skill')),
                ('majors', models.ManyToManyField(to='configuration.Major')),
                ('skills', models.ManyToManyField(related_name='skills', to='configuration.Skill')),
            ],
        ),
    ]
