# Generated by Django 4.0.3 on 2022-03-17 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speed_dating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='anything_else',
            field=models.TextField(blank=True),
        ),
    ]
