# Generated by Django 4.0.3 on 2022-03-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='availability',
        ),
        migrations.AddField(
            model_name='team',
            name='availability',
            field=models.ManyToManyField(to='configuration.sectiontime'),
        ),
    ]
