# Generated by Django 4.0.3 on 2022-03-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_team_assigned_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='number',
            field=models.SmallIntegerField(null=True, verbose_name='Team number'),
        ),
    ]
