# Generated by Django 4.0.3 on 2022-03-10 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('number', models.CharField(default='', max_length=3, primary_key=True, serialize=False)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.sectiontime')),
            ],
        ),
    ]
